# Generated by Django 4.1.1 on 2022-10-11 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question1', models.CharField(default=False, max_length=500)),
                ('question2', models.CharField(default=False, max_length=500)),
                ('question3', models.CharField(default=False, max_length=500)),
                ('question4', models.CharField(default=False, max_length=500)),
            ],
        ),
    ]
