# Generated by Django 3.2.7 on 2022-10-12 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumtek', '0005_course_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobtitle', models.CharField(default=False, max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('workDetails', models.CharField(max_length=1000)),
                ('companyName', models.CharField(max_length=50)),
                ('qualifications', models.CharField(max_length=1000)),
                ('jobtype', models.CharField(default=False, max_length=50)),
            ],
        ),
    ]
