# Generated by Django 3.2.7 on 2022-10-15 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumtek', '0006_jobinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='movie',
            new_name='csitcourse',
        ),
        migrations.AddField(
            model_name='course',
            name='courseYear',
            field=models.CharField(default=False, max_length=500),
        ),
    ]
