# Generated by Django 3.2.7 on 2022-10-15 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumtek', '0007_auto_20221015_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='slug',
        ),
    ]
