# Generated by Django 3.2.7 on 2022-10-17 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumtek', '0008_remove_course_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='rated_date',
        ),
    ]
