# Generated by Django 3.2.7 on 2022-10-24 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alumtek', '0009_remove_rating_rated_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concerns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txtName', models.CharField(default=False, max_length=500)),
                ('txtEmail', models.EmailField(default=False, max_length=500)),
                ('txtPhone', models.CharField(default=False, max_length=500)),
                ('txtMsg', models.CharField(default=False, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumni', models.IntegerField(default=1, verbose_name='Alumni')),
                ('employed', models.CharField(default=False, max_length=100)),
                ('workPlace', models.CharField(max_length=100)),
                ('yearsEmployment', models.CharField(max_length=1000)),
                ('yearGraduated', models.CharField(default=False, max_length=100)),
                ('salaryRange', models.CharField(default=False, max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='rating',
            name='user',
        ),
        migrations.AddField(
            model_name='rating',
            name='alumni',
            field=models.IntegerField(default=1, verbose_name='Alumni'),
        ),
        migrations.AlterField(
            model_name='course',
            name='csitcourse',
            field=models.CharField(default=False, max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='csitcourse',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='csitcourse+', to='alumtek.course', to_field='csitcourse'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='static/profile')),
                ('linkedIn', models.CharField(blank=True, max_length=256, null=True)),
                ('gitHub', models.CharField(blank=True, max_length=256, null=True)),
                ('facebook', models.CharField(blank=True, max_length=256, null=True)),
                ('twitter', models.CharField(blank=True, max_length=256, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
