# Generated by Django 3.2.7 on 2022-10-24 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumtek', '0010_auto_20221024_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='csitcourse',
            field=models.CharField(default=False, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='curriculum',
            field=models.CharField(default=False, max_length=255, unique=True),
        ),
    ]
