# Generated by Django 3.2.7 on 2022-10-25 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumtek', '0011_auto_20221024_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='alumni',
            field=models.IntegerField(default=1, unique=True, verbose_name='Alumni'),
        ),
    ]
