# Generated by Django 3.2.7 on 2022-11-02 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumtek', '0014_idapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idapplication',
            name='user',
        ),
        migrations.AddField(
            model_name='idapplication',
            name='alumni',
            field=models.IntegerField(default=1, unique=True, verbose_name='Alumni'),
        ),
    ]
