# Generated by Django 3.2.7 on 2022-11-02 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alumtek', '0015_auto_20221102_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idapplication',
            name='alumni',
        ),
        migrations.AddField(
            model_name='idapplication',
            name='idNumber',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='username+', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
