# Generated by Django 3.2.7 on 2022-11-12 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumtek', '0017_curriculum_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='departmentCourse',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
