# Generated by Django 3.2.7 on 2022-11-12 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumtek', '0018_course_departmentcourse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculum',
            name='department',
        ),
    ]
