# Generated by Django 3.2.7 on 2022-11-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumtek', '0019_remove_curriculum_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='alumni',
            field=models.IntegerField(default=1, unique=True, verbose_name='Alumni'),
        ),
    ]
