# Generated by Django 3.2.7 on 2022-12-08 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumtek', '0020_questions_alumni'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='curriculum',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='curriculum+', to='alumtek.curriculum', to_field='curriculum'),
        ),
    ]
